import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#c0c1ff",
        "on-background": "#dae2fd",
        "on-tertiary": "#242f52",
        "error-container": "#93000a",
        "surface-variant": "#2d3449",
        "tertiary-container": "#848fb8",
        "on-secondary-fixed-variant": "#2f3aa3",
        "on-error": "#690005",
        "surface-dim": "#0b1326",
        "outline-variant": "#464554",
        "on-secondary-fixed": "#000767",
        "on-tertiary-fixed": "#0d1a3c",
        "primary-container": "#8083ff",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#060e20",
        "on-primary-fixed-variant": "#2f2ebe",
        "primary-fixed": "#e1e0ff",
        primary: "#c0c1ff",
        "on-secondary-container": "#a8afff",
        "surface-container-highest": "#2d3449",
        "inverse-on-surface": "#283044",
        "on-primary": "#1000a9",
        "secondary-container": "#2f3aa3",
        "on-secondary": "#131e8c",
        error: "#ffb4ab",
        "on-primary-fixed": "#07006c",
        "on-primary-container": "#0d0096",
        background: "#0b1326",
        "tertiary-fixed": "#dbe1ff",
        secondary: "#bdc2ff",
        surface: "#0b1326",
        "on-surface-variant": "#c7c4d7",
        "on-tertiary-fixed-variant": "#3a456a",
        "surface-container": "#171f33",
        "on-surface": "#dae2fd",
        "surface-container-low": "#131b2e",
        "tertiary-fixed-dim": "#bac5f0",
        tertiary: "#bac5f0",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-container": "#1d284b",
        "secondary-fixed": "#e0e0ff",
        "inverse-surface": "#dae2fd",
        "surface-container-high": "#222a3d",
        "secondary-fixed-dim": "#bdc2ff",
        "surface-bright": "#31394d",
        "inverse-primary": "#494bd6",
        outline: "#908fa0",
        success: "#10b981",
        "on-success": "#ffffff",
        amber: "#fbbf24",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        md: "24px",
        gutter: "24px",
        "container-max": "600px",
        lg: "48px",
        xs: "4px",
        base: "8px",
        sm: "12px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
      },
      keyframes: {
        shake: {
          "10%, 90%": { transform: "translate3d(-1px, 0, 0)" },
          "20%, 80%": { transform: "translate3d(2px, 0, 0)" },
          "30%, 50%, 70%": { transform: "translate3d(-4px, 0, 0)" },
          "40%, 60%": { transform: "translate3d(4px, 0, 0)" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(192, 193, 255, 0.4)" },
          "50%": { boxShadow: "0 0 0 10px rgba(192, 193, 255, 0)" },
        },
        confetti: {
          "0%": { transform: "translateY(0) rotate(0deg)", opacity: "1" },
          "100%": { transform: "translateY(-200px) rotate(720deg)", opacity: "0" },
        },
      },
      animation: {
        shake: "shake 0.5s cubic-bezier(.36,.07,.19,.97) both",
        "fade-in": "fade-in 0.4s ease-out both",
        "scale-in": "scale-in 0.3s ease-out both",
        "slide-up": "slide-up 0.5s ease-out both",
        "pulse-glow": "pulse-glow 2s infinite",
        confetti: "confetti 1s ease-out forwards",
      },
    },
  },
  plugins: [],
};
export default config;
